### ISSUE TITLE
Add alphanumeric check for filter as names are alphanumeric.

### ISSUE THREAD

**Issue by UdhayaShan1** [AY2324S2-CS2103T-W10-1/tp#117]
- a step further to throw `ParseException` if key phrase is not a alphanumeric phrase? Can do this in `parse` of `FilterCommand` utilising `ParserUtil`. This is a optional step to improve AB3 imo.

_Originally posted by @UdhayaShan1 in https://github.com/AY2324S2-CS2103T-W10-1/tp/pull/104#pullrequestreview-1941377997_

**Comment by jyztintan** [comment]
Thanks @UdhayaShan1, can I clarify you mean to add unit tests to check if the keyphrase parameter is alphanumeric? 

Meaning check that no other symbols: "@#$%^&*", and if so return an error message to user to keep to alphanumeric characters?

Also just wondering got some people name got "@" or "s/o","d/o" HAHHAHA shld we take into account?

**Comment by jyztintan** [comment]
standardise with name check
