### ISSUE TITLE
Revert back to original list after every command

### ISSUE THREAD

**Issue by wapisai** [AY2324S2-CS2103T-W10-1/tp#147]

**Comment by wapisai** [comment]
add
`model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);`
to end of every command (except filter lol)

**Comment by jyztintan** [comment]
> add `model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);` to end of every command (except filter lol)

already does so for all commands except delete
