### ISSUE TITLE
Add tests to test new `ParserResult` and case-insensitive prefixes for `AddCommand`

### ISSUE THREAD

**Issue by UdhayaShan1** [AY2324S2-CS2103T-W10-1/tp#159]
Shortened a bit, still need add tests

_Originally posted by @UdhayaShan1 in https://github.com/AY2324S2-CS2103T-W10-1/tp/issues/150#issuecomment-2019859107_

**Comment by appleraincoat** [comment]
Case-Insensitive prefixes for AddCommand completed in v1.3. Add tests to test new ParserResult will be moved to v1.4.
