### ISSUE TITLE
[PE-D][Tester B] Example command in UG not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-1/tp#250]
## Description
![image.png](https://raw.githubusercontent.com/RyanNgWH/ped/main/files/66ea7d00-748b-4c46-a7db-59f40f690f3e.png)

Example command in UG throws an error

![image.png](https://raw.githubusercontent.com/RyanNgWH/ped/main/files/9af66514-fc69-41a0-9116-8329a1fd2df7.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: RyanNgWH/ped#3

**Comment by UdhayaShan1** [comment]
Typo, update UG
