### ISSUE TITLE
[PE-D][Tester E] Help (Individual Commands) Bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-1/tp#251]
- According to the User Guide, entering `COMMAND help` in the command box should show the help message for the specified command.

- However, entering `exit help` in the command box closes the entire application instead.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tamagochuuu/ped#3

**Comment by UdhayaShan1** [comment]
Duplicate
