### ISSUE TITLE
[PE-D][Tester D] Inaccurate field constraints

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-1/tp#257]
According to field constraints and error messages, the email `a+_b@a.asdf` should be valid

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: cocoanautz/ped#1

**Comment by UdhayaShan1** [comment]
FF

**Comment by jyztintan** [comment]
i do not understand how this is a bug. 



> a+_b@a.asdf

i believe this is a valid email..
https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1

**Comment by appleraincoat** [comment]
This is a duplicate bug, similar to issue #264 
To address your concerns @jyztintan , this is an issue with the our email regex where consecutive special characters are not accepted. Since the email contains "+_", which is valid, our app does not accept it.

**Comment by UdhayaShan1** [comment]
Yep its carried over bad regex from AB3

**Comment by UdhayaShan1** [comment]
Duplicate of #264 will close
