### ISSUE TITLE
[PE-D][Tester E] Feature Flaw with Field Constraints for 'PHONE' Field

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-1/tp#258]
![image.png](https://raw.githubusercontent.com/tamagochuuu/ped/main/files/973b1c38-c870-4618-8754-5704388ca0ef.png)

- As can be seen from the image above, the number `888878787` is a valid number for the PHONE field.

- Allowing any number that is greater than 3 digits for the PHONE field makes Realodex rather error-prone. In the above example, the user will not be able to tell whether the correct phone number is 88887878 or 88887877. 

- A possible improvement would be for Realodex to take in the country code of the phone number to be inputted, and check the length of the given number to decrease the chances of the user entering the wrong number.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: tamagochuuu/ped#6

**Comment by UdhayaShan1** [comment]
FF/feature suggestion

**Comment by jyztintan** [comment]
I do not think this is not a bug at all, and if so is definitely outofscope. We never specified that our product is targetted for users with 8-digit hand phone numbers. 

> * A possible improvement would be for Realodex to take in the country code of the phone number to be inputted, and check the length of the given number to decrease the chances of the user entering the wrong number.
I think this is a good suggestion but we should consider warning users, not blocking if not it could be classified as overzealous input validation.
<img width="576" alt="image" src="https://github.com/AY2324S2-CS2103T-W10-1/tp/assets/98398940/3c874ba5-6c46-44fb-b2e1-8b18be33c65a">

**Comment by UdhayaShan1** [comment]
I think superseded by #278
