### ISSUE TITLE
[PE-D][Tester B] Name is too restrictive

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-1/tp#259]
![image.png](https://raw.githubusercontent.com/RyanNgWH/ped/main/files/102aa904-0881-4622-ad98-52f028126e20.png)

Name field does not allow `s/o` or names in other languages such as chinese

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: RyanNgWH/ped#6

**Comment by UdhayaShan1** [comment]
Straight to DG
