### ISSUE TITLE
[PE-D][Tester A] Email validation is not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-1/tp#260]
On editing the email of an entry to be `InvalidEmail@InvalidDomain`, the application accepts it as a valid email even though the domain is invalid. That is, there's no ".com" or ".org", etc after the "@" symbol in the entry, but the app seems to accept it.

![image.png](https://raw.githubusercontent.com/PyromancerBoom/ped/main/files/c26128ec-388f-488f-9d91-4a7b5a5f18bb.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: PyromancerBoom/ped#6

**Comment by UdhayaShan1** [comment]
Did we say domain must contain .com?

**Comment by 4llysa** [comment]
The use of top-level domain (TLD) extensions like .com or . net at the end of an email address is not a requirement

**Comment by jyztintan** [comment]
https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1
https://github.com/nus-cs2103-AY2021S2/pe-dev-response/issues/3132
