### ISSUE TITLE
[PE-D][Tester A] Email regex not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-1/tp#264]
It is mentioned that "The the local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-). The local-part may not start or end with any special characters." 

So the email `john-a-b-c-d-e-f.-+randomSomething@gmail.com` is valid, but is not considered by the application:

![image.png](https://raw.githubusercontent.com/PyromancerBoom/ped/main/files/09a0d55d-c367-4719-92d4-b5744762cc7c.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: PyromancerBoom/ped#8

**Comment by UdhayaShan1** [comment]
Apparently we cannot have consecutive special characters
