### ISSUE TITLE
[PE-D][Tester B]  Error message does not match UG - delete with both index and name

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-1/tp#265]
![image.png](https://raw.githubusercontent.com/RyanNgWH/ped/main/files/330c8148-7ba0-4a97-8fc1-a744d1b69cac.png)

![image.png](https://raw.githubusercontent.com/RyanNgWH/ped/main/files/7fd50c55-3319-42a0-be1c-021196507ea0.png)

Error message shown does not match what is said in the UG

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: RyanNgWH/ped#8

**Comment by UdhayaShan1** [comment]
I think UG bug missing " to end the error

**Comment by wapisai** [comment]
Yup, will add that
