### ISSUE TITLE
[PE-D][Tester D] Filter works with invalid strings 3 letters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-1/tp#267]
The commands `filter apr ThisShouldwork` and `filter aprThisShoulntWork` work although documentation states dates are filtered with MMM format.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: cocoanautz/ped#2

**Comment by UdhayaShan1** [comment]
@jyztintan assuming its cause of the `List<String> keyphrases` can probably update UG say we are forgiving in input and accepts whatever first string?

![image](https://github.com/AY2324S2-CS2103T-W10-1/tp/assets/39399745/853b8154-123e-40bb-a795-8e113df9317d)

**Comment by jyztintan** [comment]
Not sure, could be Java's datetime package is able to read the input based on the first few characters, maybe @4llysa can explain also.

**Comment by 4llysa** [comment]
Yes it's due to Java DateTime funny funny stuff because it is not strict to 3 letters. It can be fixed by validating that input length is 3. Since this is a bug mentioned in the UG and not an enhancement I think I am allowed to fix it. @AY2324S2-CS2103T-W10-1/developers cfm pls

**Comment by jyztintan** [comment]
Actually I'm not sure if we should "fix" it because I thought it makes sense to standardise MMM format with whatever Java's format is. I think not a big deal because this bug report is confirm outofscope anyways.

**Comment by UdhayaShan1** [comment]
Idt can fix cause it's not technically incorrect behaviour just a forgiving one so idt it's a issue oso

**Comment by appleraincoat** [comment]
I believe there is no need to fix. Perhaps it is worth mentioning this forgiving behavior in the UG/DG though.

**Comment by jyztintan** [comment]
@4llysa any other thoughts if not think we can close

**Comment by UdhayaShan1** [comment]
Will close I dont think we have to mention this in UG
