### ISSUE TITLE
[PE-D][Tester D] Documentation inconsistency

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-1/tp#270]
Birthday of `4apr000002023` works although document states that birthday needs to be in `DDMMMYYYY` format.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: cocoanautz/ped#3

**Comment by UdhayaShan1** [comment]
@4llysa i think have basis to reject on ground of forgiving erroneous input can add to UG as well

![image](https://github.com/AY2324S2-CS2103T-W10-1/tp/assets/39399745/84b5031f-6d10-4f65-82d1-876889dfbe14)

**Comment by 4llysa** [comment]
@UdhayaShan1 I agree with you. such an input was recognised by realodex as the correct date and application does not misbehave. other related features like sorting by birthday works as expected 👍🏻

**Comment by UdhayaShan1** [comment]
Will close
