### ISSUE TITLE
[PE-D][Tester D] User Guide inconsistency

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W10-1/tp#271]
User guide inconsistent with help window shown in client. 

Help window mentions that `COMMAND help` only works with some commands, whereas UG does not state this constraint.

![image.png](https://raw.githubusercontent.com/cocoanautz/ped/main/files/82b282ff-596c-434f-ac56-0a015fb1e1e7.png)

![image.png](https://raw.githubusercontent.com/cocoanautz/ped/main/files/034204ba-2ccf-47f4-8623-a158ba2f2856.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: cocoanautz/ped#4

**Comment by UdhayaShan1** [comment]
@appleraincoat UG update
