### ISSUE TITLE
[PE-D][Tester D] Filter error message is not specific

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-1/tp#274]
`filter asd` Give the error message that it needs to be in MMM format, whereas it would be more specific to state that `asd` is not a valid month`

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: cocoanautz/ped#6

**Comment by UdhayaShan1** [comment]
@4llysa uty i think the error is specific enough, hence not valid

**Comment by 4llysa** [comment]
Specific output from realodex 
```
Birth Month should be in MMM format.
Example: b/Sep
```

I believe that it is specific enough as  output specifics "birth month", "MMM" format and gives an example.

**Comment by UdhayaShan1** [comment]
Will close
