### ISSUE TITLE
[PE-D][Tester B] Add command has too many mandatory fields

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W10-1/tp#279]
`add n/NAME p/PHONE i/INCOME e/EMAIL a/ADDRESS f/FAMILY t/TAG h/HOUSING t/TYPE [r/REMARK] [b/BIRTHDAY]`

Having 8 required fields just to add a client to the address book is too troublesome, especially if I do not have certain information such as address

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: RyanNgWH/ped#12

**Comment by UdhayaShan1** [comment]
@4llysa i think these are important for day-to-day real estate work? maybe we can justify by adding to ug

**Comment by 4llysa** [comment]
perhaps we can list this in our 10 FeatureFlaws.

There is some overlap with this and other issues raised on inappropriate fields. Like if i am a buyer, why do u need my address? or if i am a seller, does my family size matter?

**Comment by UdhayaShan1** [comment]
Options

- Put in DG that we plan to make fields optional based on type of buyer status in future, for now we keep all mostly compulsory
- Argue in UG that they can put `0` for income if they wish not to but again this might be FF as might as well make income optional
- Argue in UG with logic
