### ISSUE TITLE
Update User Guide based on v1.2 features

### ISSUE THREAD

**Issue by 4llysa** [AY2324S2-CS2103T-W10-1/tp#87]
<img width="787" alt="image" src="https://github.com/AY2324S2-CS2103T-W10-1/tp/assets/59839013/6d947585-bd59-44d2-a411-e5061b3299eb">
^ the above add command is not in the correct format

Update the user guide to reflect changes of v1.2

**Comment by jyztintan** [comment]
Modified find feature to filter feature, and detailing its new behaviour in UG
